import { FormEvent, useEffect, useState } from 'react';
import './styles.css';
import LocationPicker from './LocationPicker';
const API = 'https://api.evazmelk.ir';
type Ref = {id:string;name:string;code?:string;slug?:string};
const months=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];
const initial={public_code:'',property_type_id:'',region_id:'',neighborhood:'',address:'',area_m2:'',building_area_m2:'',commercial_area_m2:'',usage_type:'',status:'آگهی فروش',asking_price_toman:'',registration_year:'',registration_month_name:'',notes:'',street_width:'',street_frontage_m:'',mehr_block:'',mehr_floor:'',mehr_unit:'',national_phase:'',national_stage:'',national_notes:'',build_year:'',bedrooms:'',sale_date:'',sale_price_toman:'',sale_notes:'',latitude:'',longitude:''};
type Form = typeof initial;
const numeric=['area_m2','building_area_m2','commercial_area_m2','asking_price_toman','street_width','street_frontage_m','mehr_floor','build_year','bedrooms','sale_price_toman','latitude','longitude'];
export default function App(){
 const [token,setToken]=useState(localStorage.getItem('evazmelk_admin_token'));
 const [email,setEmail]=useState(''),[password,setPassword]=useState('');
 const [section,setSection]=useState('ثبت ملک'),[error,setError]=useState(''),[saved,setSaved]=useState(''),[busy,setBusy]=useState(false);
 const [types,setTypes]=useState<Ref[]>([]),[regions,setRegions]=useState<Ref[]>([]),[items,setItems]=useState<any[]>([]);
 const [editingLocation,setEditingLocation]=useState<{code:string;lat:string;lng:string}|null>(null);
 const [form,setForm]=useState<Form>(initial);
 const [range,setRange]=useState({region_id:'',property_type_id:'',period:'',low_price_toman:'',high_price_toman:''});
 const set=(key:keyof Form,value:string)=>setForm(v=>({...v,[key]:value}));
 async function request(path:string,options:RequestInit={}){const r=await fetch(API+path,{...options,headers:{Authorization:`Bearer ${token}`,...options.headers}});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'درخواست انجام نشد');return d;}
 useEffect(()=>{if(!token)return;let live=true;request('/api/admin/reference').then(d=>{if(live){setTypes(d.property_types);setRegions(d.regions)}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[token]);
 useEffect(()=>{if(token&&section==='املاک ثبت‌شده')request('/api/admin/properties/direct').then(d=>setItems(d.items)).catch(e=>setError(e.message))},[token,section]);
 async function login(e:FormEvent){e.preventDefault();setError('');try{const r=await fetch(API+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw Error(d.detail||'ورود ناموفق بود');localStorage.setItem('evazmelk_admin_token',d.access_token);setToken(d.access_token)}catch(x){setError(x instanceof Error?x.message:'خطای اتصال')}}
 async function saveProperty(e:FormEvent){e.preventDefault();setError('');setSaved('');setBusy(true);try{const payload:any={...form,registration_month:form.registration_year&&form.registration_month_name?`${form.registration_year}/${form.registration_month_name}`:null};delete payload.registration_year;delete payload.registration_month_name;numeric.forEach(k=>payload[k]=form[k as keyof Form]===''?null:Number(form[k as keyof Form]));for(const k of Object.keys(payload))if(payload[k]==='')payload[k]=null;const d=await request('/api/admin/properties/direct',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});setSaved(`ملک ${d.public_code} ثبت شد.`);setForm(initial)}catch(x){setError(x instanceof Error?x.message:'ثبت انجام نشد')}finally{setBusy(false)}}
 async function saveRange(e:FormEvent){e.preventDefault();setError('');setSaved('');setBusy(true);try{await request('/api/admin/price-ranges',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...range,low_price_toman:Number(range.low_price_toman),high_price_toman:Number(range.high_price_toman)})});setSaved('بازهٔ قیمت شاخص ذخیره شد.')}catch(x){setError(x instanceof Error?x.message:'ثبت انجام نشد')}finally{setBusy(false)}}
 async function saveLocation(e:FormEvent){e.preventDefault();if(!editingLocation)return;setError('');setSaved('');setBusy(true);try{if((!!editingLocation.lat)!=(!!editingLocation.lng))throw Error('هر دو مختصات را وارد کنید.');await request(`/api/admin/properties/${encodeURIComponent(editingLocation.code)}/location`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({latitude:editingLocation.lat?Number(editingLocation.lat):null,longitude:editingLocation.lng?Number(editingLocation.lng):null})});const d=await request('/api/admin/properties/direct');setItems(d.items);setSaved(`موقعیت ملک ${editingLocation.code} ذخیره شد.`);setEditingLocation(null)}catch(x){setError(x instanceof Error?x.message:'ثبت موقعیت انجام نشد')}finally{setBusy(false)}}
 const field=(key:keyof Form,label:string,kind='text',required=false)=><label key={key}>{label}<input type={kind} min={kind==='number'?'0':undefined} required={required} value={form[key]} onChange={e=>set(key,e.target.value)}/></label>;
 const select=(key:keyof Form,label:string,options:{value:string;label:string}[],required=false)=><label>{label}<select required={required} value={form[key]} onChange={e=>set(key,e.target.value)}><option value="">انتخاب کنید</option>{options.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>;
 if(!token)return <main className="login" dir="rtl"><div className="card"><div className="mark">خ</div><h1>خودمونی</h1><p>ورود به مدیریت املاک اوز</p><form onSubmit={login}><label>ایمیل<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>رمز عبور<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button>ورود</button></form></div></main>;
 return <div className="shell" dir="rtl"><aside><div className="brand"><span className="mark small">خ</span>خودمونی</div><div className="muted">مدیریت املاک اوز</div>{['ثبت ملک','املاک ثبت‌شده','قیمت شاخص'].map(x=><button key={x} className={section===x?'nav active':'nav'} onClick={()=>{setSection(x);setError('');setSaved('')}}>{x}</button>)}<button className="logout" onClick={()=>{localStorage.removeItem('evazmelk_admin_token');setToken(null)}}>خروج</button></aside><main className="content"><header><h1>{section}</h1></header>
 {section==='ثبت ملک'&&<form className="entry" onSubmit={saveProperty}><div className="panel"><h2>مشخصات ملک</h2><div className="fields">{field('public_code','کد ملک', 'text',true)}{select('property_type_id','نوع ملک',types.map(t=>({value:t.id,label:t.name})),true)}{select('region_id','منطقه',regions.filter(r=>r.slug?.startsWith('R-')).map(r=>({value:r.id,label:`${r.slug} — ${r.name}`})),true)}{field('neighborhood','محله')}{field('address','آدرس')}{field('area_m2','متراژ زمین (مترمربع)','number')}{field('building_area_m2','زیربنا (مترمربع)','number')}{field('usage_type','کاربری')}{select('status','وضعیت ملک',['آگهی فروش','فروخته شده','لغو شده'].map(x=>({value:x,label:x})),true)}{field('asking_price_toman','قیمت پیشنهادی (تومان)','number',form.status==='آگهی فروش')}{field('registration_year','سال ثبت (شمسی)','number')}{select('registration_month_name','ماه ثبت',months.map(x=>({value:x,label:x})))}<label className="wide">توضیحات<textarea value={form.notes} onChange={e=>set('notes',e.target.value)}/></label></div></div>
 <div className="panel"><h2>جزئیات تکمیلی</h2><p className="hint">فیلدهای مربوط به نوع ملک را پر کنید؛ بقیه می‌توانند خالی بمانند.</p><div className="fields">{field('street_width','زمین: عرض گذر (متر)','number')}{field('street_frontage_m','زمین: بر خیابان (متر)','number')}{field('mehr_block','مسکن مهر: بلوک')}{field('mehr_floor','مسکن مهر: طبقه','number')}{field('mehr_unit','مسکن مهر: واحد')}{field('national_phase','مسکن ملی: فاز')}{select('national_stage','مسکن ملی: مرحله ساخت',['مرحله سقف اول','مرحله سقف دوم','اتمام اسکلت کامل','اسکلت + تأسیسات کامل','تأسیسات + نما','کامل‌شده'].map(x=>({value:x,label:x})))}{field('national_notes','مسکن ملی: توضیحات')}{field('build_year','ساختمان: سال ساخت','number')}{field('bedrooms','ساختمان: تعداد خواب','number')}{field('commercial_area_m2','تجاری: متراژ (مترمربع)','number')}</div></div>
 <div className="panel"><LocationPicker lat={form.latitude} lng={form.longitude} onChange={(lat,lng)=>setForm(v=>({...v,latitude:lat,longitude:lng}))}/></div>
 {form.status==='فروخته شده'&&<div className="panel"><h2>معامله انجام‌شده</h2><div className="fields">{field('sale_date','تاریخ معامله (شمسی)', 'text',true)}{field('sale_price_toman','قیمت معامله (تومان)','number',true)}{field('sale_notes','توضیحات معامله')}</div></div>}
 {error&&<div className="error" role="alert">{error}</div>}{saved&&<div className="success" role="status">{saved}</div>}<button disabled={busy} className="submit">{busy?'در حال ثبت…':'ثبت ملک'}</button></form>}
 {section==='املاک ثبت‌شده'&&<div className="panel"><h2>آخرین املاک</h2><div className="table-wrap"><table><thead><tr><th>کد</th><th>نوع</th><th>منطقه</th><th>وضعیت</th><th>متراژ</th><th>قیمت پیشنهادی / معامله</th><th>نقشه</th></tr></thead><tbody>{items.map((p,i)=><tr key={i}><td>{p.public_code}</td><td>{p.property_type}</td><td>{p.region||'—'}</td><td>{p.status}</td><td>{p.area_m2||'—'}</td><td>{p.asking_price_toman||p.sale_price_toman||'—'}</td><td><button type="button" className="secondary" onClick={()=>{setEditingLocation({code:p.public_code,lat:p.latitude==null?'':String(p.latitude),lng:p.longitude==null?'':String(p.longitude)});setSaved('');setError('')}}>{p.latitude==null?'تعیین موقعیت':'اصلاح موقعیت'}</button></td></tr>)}</tbody></table></div>{items.length===0&&<p>هنوز ملکی برای نمایش ثبت نشده است.</p>}{editingLocation&&<form className="location-edit" onSubmit={saveLocation}><h3>موقعیت ملک {editingLocation.code}</h3><LocationPicker lat={editingLocation.lat} lng={editingLocation.lng} onChange={(lat,lng)=>setEditingLocation(v=>v?{...v,lat,lng}:v)}/><div className="actions"><button disabled={busy}>ذخیرهٔ موقعیت</button><button type="button" className="secondary" onClick={()=>setEditingLocation(null)}>انصراف</button></div></form>}</div>}
 {section==='قیمت شاخص'&&<div className="panel"><h2>بازهٔ قیمت ماهانه</h2><p className="hint">قیمت شاخص را مدیر مستقل از قیمت آگهی‌ها و معاملات وارد می‌کند.</p><form className="fields" onSubmit={saveRange}><label>منطقه<select required value={range.region_id} onChange={e=>setRange(v=>({...v,region_id:e.target.value}))}><option value="">انتخاب کنید</option>{regions.filter(r=>r.slug?.startsWith('R-')).map(r=><option key={r.id} value={r.id}>{r.slug} — {r.name}</option>)}</select></label><label>نوع ملک<select required value={range.property_type_id} onChange={e=>setRange(v=>({...v,property_type_id:e.target.value}))}><option value="">انتخاب کنید</option>{types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>ماه (شمسی)<input required placeholder="۱۴۰۵/شهریور" value={range.period} onChange={e=>setRange(v=>({...v,period:e.target.value}))}/></label><label>حد پایین (تومان)<input required type="number" min="1" value={range.low_price_toman} onChange={e=>setRange(v=>({...v,low_price_toman:e.target.value}))}/></label><label>حد بالا (تومان)<input required type="number" min="1" value={range.high_price_toman} onChange={e=>setRange(v=>({...v,high_price_toman:e.target.value}))}/></label><button disabled={busy} className="submit">ذخیره بازه</button></form></div>}
 {section!=='ثبت ملک'&&error&&<div className="error" role="alert">{error}</div>}{section!=='ثبت ملک'&&saved&&<div className="success" role="status">{saved}</div>}
 </main></div>;
}
