import { FormEvent, useState } from 'react';
const API = 'https://api.evazmelk.ir';

export default function App() {
  const [token, setToken] = useState(localStorage.getItem('evazmelk_admin_token'));
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const [section, setSection] = useState('نمای کلی'); const [code, setCode] = useState(''); const [typeId, setTypeId] = useState(''); const [area, setArea] = useState(''); const [year, setYear] = useState(''); const [saved, setSaved] = useState('');
  async function login(e: FormEvent) { e.preventDefault(); setError(''); try { const r = await fetch(`${API}/api/auth/login`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({email,password}) }); const d=await r.json(); if(!r.ok) throw Error(d.detail||'ورود ناموفق بود'); localStorage.setItem('evazmelk_admin_token',d.access_token); setToken(d.access_token); } catch(x) { setError(x instanceof Error?x.message:'خطای اتصال به سرور'); } }
  async function saveProperty(e: FormEvent) { e.preventDefault(); setError(''); setSaved(''); try { const r=await fetch(`${API}/api/admin/properties`, {method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({public_code:code,property_type_id:typeId,area_m2:area?Number(area):null,build_year:year?Number(year):null})}); const d=await r.json(); if(!r.ok) throw Error(d.detail||'ثبت ملک ناموفق بود'); setSaved(`ملک ${d.public_code} با موفقیت ثبت شد`); setCode('');setArea('');setYear(''); } catch(x) { setError(x instanceof Error?x.message:'خطای اتصال به سرور'); } }
  if (!token) return <main className="login"><div className="card"><div className="mark">خ</div><h1>خودمونی</h1><p>ورود به پنل مدیریت شاخص املاک اوز</p><form onSubmit={login}><label>ایمیل<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} /></label><label>رمز عبور<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} /></label>{error&&<div className="error">{error}</div>}<button>ورود امن</button></form></div></main>;
  const content = section === 'املاک' ? <div className="panel"><h2>ثبت ملک جدید</h2><p>شناسهٔ نوع ملک را از جدول <code>app.property_types</code> در Supabase کپی کن.</p><form className="property-form" onSubmit={saveProperty}><label>کد داخلی ملک<input required value={code} onChange={e=>setCode(e.target.value)} placeholder="EV-0001" /></label><label>شناسهٔ نوع ملک<input required value={typeId} onChange={e=>setTypeId(e.target.value)} /></label><label>مساحت (مترمربع)<input type="number" min="1" value={area} onChange={e=>setArea(e.target.value)} /></label><label>سال ساخت<input type="number" min="1300" value={year} onChange={e=>setYear(e.target.value)} /></label>{error&&<div className="error">{error}</div>}{saved&&<div className="success">{saved}</div>}<button>ذخیرهٔ ملک</button></form></div> : section === 'نمای کلی' ? <div className="grid"><article><span>املاک ثبت‌شده</span><strong>—</strong><small>آمادهٔ ورود داده</small></article><article><span>معاملات تأییدشده</span><strong>—</strong><small>منبع عمومی هنوز خالی است</small></article><article><span>آخرین شاخص</span><strong>—</strong><small>پس از انتشار نمایش داده می‌شود</small></article></div> : <div className="panel"><h2>ماژول {section}</h2><p>این بخش در مرحلهٔ بعدی فعال می‌شود.</p></div>;
  return <div className="shell" dir="rtl"><aside><div className="brand"><span className="mark small">خ</span><span>خودمونی</span></div><div className="muted">پنل مدیریت</div>{['نمای کلی','املاک','معاملات','آگهی‌ها','شاخص‌ها','گزارش‌های ماهانه'].map(x=><button key={x} className={section===x?'nav active':'nav'} onClick={()=>{setSection(x);setError('');}}>{x}</button>)}<button className="logout" onClick={()=>{localStorage.removeItem('evazmelk_admin_token');setToken(null)}}>خروج</button></aside><section className="content"><header><div><h1>{section}</h1><p>داده‌های خصوصی و عملیاتی پروژه</p></div><span className="status">API متصل</span></header>{content}</section></div>;
}
