import { pgTable, uuid, text, bigint, integer, boolean, timestamp, date, numeric, jsonb, uniqueIndex, index } from "drizzle-orm/pg-core";

export const regions = pgTable("regions", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), slug: text("slug").notNull(), isPublic: boolean("is_public").default(true).notNull(), createdAt: timestamp("created_at", {withTimezone:true}).defaultNow().notNull() }, t => ({slugUq: uniqueIndex("regions_slug_uq").on(t.slug)}));
export const neighborhoods = pgTable("neighborhoods", { id: uuid("id").defaultRandom().primaryKey(), regionId: uuid("region_id").notNull().references(()=>regions.id), name: text("name").notNull(), slug: text("slug").notNull(), validFrom: date("valid_from").notNull(), validTo: date("valid_to"), isPublic: boolean("is_public").default(true).notNull() }, t => ({regionNameUq: uniqueIndex("neighborhoods_region_name_uq").on(t.regionId,t.name), slugIdx:index("neighborhoods_slug_idx").on(t.slug)}));
export const propertyTypes = pgTable("property_types", { id: uuid("id").defaultRandom().primaryKey(), code: text("code").notNull().unique(), name: text("name").notNull(), category: text("category").notNull() });
export const properties = pgTable("properties", { id: uuid("id").defaultRandom().primaryKey(), publicCode: text("public_code").notNull().unique(), propertyTypeId: uuid("property_type_id").notNull().references(()=>propertyTypes.id), areaM2: numeric("area_m2",{precision:12,scale:2}), buildingAreaM2: numeric("building_area_m2",{precision:12,scale:2}), floor: integer("floor"), buildYear: integer("build_year"), status: text("status").default("active").notNull(), privateAddress: text("private_address"), createdAt: timestamp("created_at",{withTimezone:true}).defaultNow().notNull() }, t=>({typeIdx:index("properties_type_idx").on(t.propertyTypeId)}));
export const marketRecords = pgTable("market_records", { id: uuid("id").defaultRandom().primaryKey(), propertyId: uuid("property_id").references(()=>properties.id), recordMonth: date("record_month").notNull(), propertyTypeId: uuid("property_type_id").notNull().references(()=>propertyTypes.id), regionId: uuid("region_id").notNull().references(()=>regions.id), neighborhoodId: uuid("neighborhood_id").references(()=>neighborhoods.id), regionNameSnapshot: text("region_name_snapshot").notNull(), neighborhoodNameSnapshot: text("neighborhood_name_snapshot"), sourceId: uuid("source_id"), status: text("status").default("raw").notNull(), isPublic: boolean("is_public").default(false).notNull(), createdAt: timestamp("created_at",{withTimezone:true}).defaultNow().notNull() }, t=>({monthTypeIdx:index("market_records_month_type_idx").on(t.recordMonth,t.propertyTypeId), publicIdx:index("market_records_public_idx").on(t.isPublic,t.recordMonth)}));
export const transactions = pgTable("transactions", { id: uuid("id").defaultRandom().primaryKey(), marketRecordId: uuid("market_record_id").notNull().unique().references(()=>marketRecords.id), transactionMonth: date("transaction_month").notNull(), finalPriceToman: bigint("final_price_toman",{mode:"number"}).notNull(), pricePerM2Toman: bigint("price_per_m2_toman",{mode:"number"}), verifiedAt: timestamp("verified_at",{withTimezone:true}), isPublic: boolean("is_public").default(false).notNull() }, t=>({monthIdx:index("transactions_month_idx").on(t.transactionMonth)}));
export const listings = pgTable("listings", { id: uuid("id").defaultRandom().primaryKey(), marketRecordId: uuid("market_record_id").notNull().unique().references(()=>marketRecords.id), askingPriceToman: bigint("asking_price_toman",{mode:"number"}).notNull(), pricePerM2Toman: bigint("price_per_m2_toman",{mode:"number"}), publishedAt: timestamp("published_at",{withTimezone:true}), closedAt: timestamp("closed_at",{withTimezone:true}), status: text("status").default("draft").notNull(), isPublic: boolean("is_public").default(false).notNull() }, t=>({statusIdx:index("listings_status_idx").on(t.status,t.publishedAt)}));
export const listingPriceHistory = pgTable("listing_price_history", { id: uuid("id").defaultRandom().primaryKey(), listingId: uuid("listing_id").notNull().references(()=>listings.id), oldPriceToman: bigint("old_price_toman",{mode:"number"}), newPriceToman: bigint("new_price_toman",{mode:"number"}).notNull(), changedAt: timestamp("changed_at",{withTimezone:true}).defaultNow().notNull(), changedBy: uuid("changed_by"), reason: text("reason") }, t=>({listingTimeIdx:index("listing_price_history_idx").on(t.listingId,t.changedAt)}));
export const priceIndices = pgTable("price_indices", { id: uuid("id").defaultRandom().primaryKey(), propertyTypeId: uuid("property_type_id").notNull().references(()=>propertyTypes.id), regionId: uuid("region_id").references(()=>regions.id), period: date("period").notNull(), value: numeric("value",{precision:14,scale:4}).notNull(), changePct: numeric("change_pct",{precision:9,scale:4}), sampleCount: integer("sample_count").notNull(), confidenceLevel: text("confidence_level").notNull(), formulaVersion: text("formula_version").notNull(), isPublic: boolean("is_public").default(false).notNull() }, t=>({periodTypeIdx:index("price_indices_period_type_idx").on(t.period,t.propertyTypeId), uq:uniqueIndex("price_indices_uq").on(t.propertyTypeId,t.regionId,t.period,t.formulaVersion)}));
export const liquidityIndices = pgTable("liquidity_indices", { id: uuid("id").defaultRandom().primaryKey(), regionId: uuid("region_id").notNull().references(()=>regions.id), period: date("period").notNull(), score: numeric("score",{precision:8,scale:4}), medianDaysOnMarket: numeric("median_days_on_market",{precision:10,scale:2}), listingToTransactionRate: numeric("listing_to_transaction_rate",{precision:8,scale:4}), inventoryTurnoverRate: numeric("inventory_turnover_rate",{precision:8,scale:4}), saleToAskRatio: numeric("sale_to_ask_ratio",{precision:8,scale:4}), sampleCount: integer("sample_count").notNull(), confidenceLevel: text("confidence_level").notNull(), formulaVersion: text("formula_version").notNull(), isPublic: boolean("is_public").default(false).notNull() }, t=>({uq:uniqueIndex("liquidity_indices_uq").on(t.regionId,t.period,t.formulaVersion)}));
export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), email: text("email").notNull().unique(), passwordHash: text("password_hash").notNull(), role: text("role").notNull(), twoFactorEnabled: boolean("two_factor_enabled").default(false).notNull(), isActive: boolean("is_active").default(true).notNull(), createdAt: timestamp("created_at",{withTimezone:true}).defaultNow().notNull() });
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(()=>users.id), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: uuid("entity_id"), beforeData: jsonb("before_data"), afterData: jsonb("after_data"), createdAt: timestamp("created_at",{withTimezone:true}).defaultNow().notNull() }, t=>({entityIdx:index("audit_logs_entity_idx").on(t.entityType,t.entityId), timeIdx:index("audit_logs_time_idx").on(t.createdAt)}));
export const monthlyReports = pgTable("monthly_reports", { id: uuid("id").defaultRandom().primaryKey(), period: date("period").notNull().unique(), title: text("title").notNull(), body: text("body"), status: text("status").default("draft").notNull(), publishedAt: timestamp("published_at",{withTimezone:true}) });
export const specialOpportunities = pgTable("special_opportunities", { id: uuid("id").defaultRandom().primaryKey(), propertyId: uuid("property_id").references(()=>properties.id), month: date("month").notNull().unique(), reason: text("reason").notNull(), status: text("status").default("draft").notNull(), isPublic: boolean("is_public").default(false).notNull() });
export const dataSources = pgTable("data_sources", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), sourceType: text("source_type").notNull(), reference: text("reference"), reliability: text("reliability") });
export const socialContentTemplates = pgTable("social_content_templates", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), contentType: text("content_type").notNull(), template: text("template").notNull(), isActive: boolean("is_active").default(true).notNull() });
export const socialContentAssets = pgTable("social_content_assets", { id: uuid("id").defaultRandom().primaryKey(), templateId: uuid("template_id").references(()=>socialContentTemplates.id), reportId: uuid("report_id").references(()=>monthlyReports.id), storageKey: text("storage_key").notNull(), mimeType: text("mime_type").notNull(), status: text("status").default("draft").notNull(), createdAt: timestamp("created_at",{withTimezone:true}).defaultNow().notNull() });
