import {useEffect,useRef,useState} from 'react';
const API='https://api.evazmelk.ir';
const KEY=import.meta.env.VITE_GOOGLE_MAPS_API_KEY as string|undefined;
const EVaz={lat:27.7600,lng:54.0073};
type Listing={public_code:string;property_type:string;category:string;region:string|null;area_m2:number|null;building_area_m2:number|null;latitude:number;longitude:number;asking_price_toman:number};
declare global {interface Window {google:any;__evazMapsPromise?:Promise<any>}}
function loadGoogle(){if(window.google?.maps)return Promise.resolve(window.google);if(window.__evazMapsPromise)return window.__evazMapsPromise;window.__evazMapsPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(KEY||'')}&v=weekly&language=fa&region=IR`;script.async=true;script.onload=()=>window.google?.maps?resolve(window.google):reject(Error('نقشه بارگذاری نشد'));script.onerror=()=>reject(Error('ارتباط با نقشه برقرار نشد'));document.head.appendChild(script)});return window.__evazMapsPromise}
function isLand(p:Listing){return p.category==='زمین'||p.category==='ملکی'||/زمین|باغ/.test(p.property_type)}
function price(value:number){return value>=1e9?`${(value/1e9).toLocaleString('fa-IR',{maximumFractionDigits:1})} میلیارد`:`${(value/1e6).toLocaleString('fa-IR',{maximumFractionDigits:0})} میلیون`}
export default function PropertyMap(){const host=useRef<HTMLDivElement>(null),mapRef=useRef<any>(null),markers=useRef<any[]>([]);const [items,setItems]=useState<Listing[]>([]),[filter,setFilter]=useState('همه'),[selected,setSelected]=useState<Listing|null>(null),[error,setError]=useState(''),[ready,setReady]=useState(false);
 useEffect(()=>{fetch(API+'/api/public/map-listings').then(async r=>{if(!r.ok)throw Error();return r.json()}).then(d=>setItems(d.items||[])).catch(()=>setError('دریافت آگهی‌ها انجام نشد.'))},[]);
 useEffect(()=>{if(!KEY){setError('کلید نقشهٔ گوگل هنوز برای سایت تنظیم نشده است.');return}let active=true;loadGoogle().then(g=>{if(!active||!host.current)return;mapRef.current=new g.maps.Map(host.current,{center:EVaz,zoom:14,mapTypeControl:false,streetViewControl:false,fullscreenControl:true,gestureHandling:'greedy'});setReady(true)}).catch(e=>setError(e.message));return()=>{active=false}},[]);
 useEffect(()=>{if(!ready||!mapRef.current)return;const g=window.google;markers.current.forEach(m=>m.setMap(null));markers.current=[];const shown=items.filter(p=>filter==='همه'||(filter==='زمین'?isLand(p):!isLand(p)));for(const p of shown){const marker=new g.maps.Marker({map:mapRef.current,position:{lat:Number(p.latitude),lng:Number(p.longitude)},title:`${p.property_type}، ${price(p.asking_price_toman)}`,icon:{path:'M -52,-36 Q -52,-48 -40,-48 L 40,-48 Q 52,-48 52,-36 L 52,-10 Q 52,2 40,2 L 8,2 L 0,13 L -8,2 L -40,2 Q -52,2 -52,-10 Z',fillColor:isLand(p)?'#ad261f':'#116a60',fillOpacity:1,strokeColor:'#fff',strokeWeight:2,labelOrigin:new g.maps.Point(0,-22)},label:{text:price(p.asking_price_toman),color:'#fff',fontSize:'12px',fontWeight:'bold'}});marker.addListener('click',()=>setSelected(p));markers.current.push(marker)}},[items,filter,ready]);
 return <div className="map-page"><div className="map-toolbar"><div><h2>املاک روی نقشهٔ اوز</h2><p>زمین و خانه‌های دارای آگهی فعال</p></div><div className="map-filters" aria-label="فیلتر نوع ملک">{['همه','زمین','خانه'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>{setFilter(x);setSelected(null)}}>{x}</button>)}</div></div><div className="map-wrap"><div className="property-map" ref={host} role="application" aria-label="نقشه آگهی‌های املاک اوز"/>{error&&<div className="map-error" role="alert">{error}</div>}{!error&&items.length===0&&<div className="map-empty">هنوز آگهیِ دارای موقعیت روی نقشه ثبت نشده است.</div>}{selected&&<aside className="map-detail"><button className="map-close" onClick={()=>setSelected(null)} aria-label="بستن جزئیات">×</button><small>{selected.public_code} · {selected.region||'اوز'}</small><h3>{selected.property_type}</h3><strong>{price(selected.asking_price_toman)} تومان</strong><p>{selected.area_m2?`${Number(selected.area_m2).toLocaleString('fa-IR')} متر زمین`:''}{selected.building_area_m2?` · ${Number(selected.building_area_m2).toLocaleString('fa-IR')} متر زیربنا`:''}</p><a href="https://wa.me/989212745755" target="_blank" rel="noopener noreferrer">پرس‌وجو دربارهٔ این ملک</a></aside>}</div><p className="map-count">{items.filter(p=>filter==='همه'||(filter==='زمین'?isLand(p):!isLand(p))).length.toLocaleString('fa-IR')} آگهی روی نقشه</p></div>
}
