import {useEffect,useRef,useState} from 'react';
const API='https://api.evazmelk.ir';
const KEY=import.meta.env.VITE_NESHAN_MAP_KEY as string|undefined;
const EVaz={lat:27.7600,lng:54.0073};
type Listing={public_code:string;property_type:string;category:string;region:string|null;area_m2:number|null;building_area_m2:number|null;latitude:number;longitude:number;asking_price_toman:number};
declare global {interface Window {L:any;__evazNeshanPromise?:Promise<any>}}
function loadNeshan(){if(window.L?.Map)return Promise.resolve(window.L);if(window.__evazNeshanPromise)return window.__evazNeshanPromise;const base='https://static.neshan.org/sdk/leaflet/v1.9.4/neshan-sdk/v1.0.8/';window.__evazNeshanPromise=new Promise((resolve,reject)=>{if(!document.querySelector('link[data-evaz-neshan]')){const css=document.createElement('link');css.rel='stylesheet';css.href=base+'index.css';css.dataset.evazNeshan='';document.head.appendChild(css)}const script=document.createElement('script');script.src=base+'index.js';script.async=true;script.onload=()=>window.L?.Map?resolve(window.L):reject(Error('نقشهٔ نشان بارگذاری نشد.'));script.onerror=()=>reject(Error('ارتباط با نقشهٔ نشان برقرار نشد.'));document.head.appendChild(script)}).catch(e=>{window.__evazNeshanPromise=undefined;throw e});return window.__evazNeshanPromise}
function isLand(p:Listing){return p.category==='زمین'||p.category==='ملکی'||/زمین|باغ/.test(p.property_type)}
function price(value:number){return value>=1e9?`${(value/1e9).toLocaleString('fa-IR',{maximumFractionDigits:1})} میلیارد`:`${(value/1e6).toLocaleString('fa-IR',{maximumFractionDigits:0})} میلیون`}
export default function PropertyMap(){const host=useRef<HTMLDivElement>(null),mapRef=useRef<any>(null),markers=useRef<any[]>([]);const [items,setItems]=useState<Listing[]>([]),[filter,setFilter]=useState('همه'),[selected,setSelected]=useState<Listing|null>(null),[error,setError]=useState(''),[ready,setReady]=useState(false);
 useEffect(()=>{fetch(API+'/api/public/map-listings').then(async r=>{if(!r.ok)throw Error();return r.json()}).then(d=>setItems(d.items||[])).catch(()=>setError('دریافت آگهی‌ها انجام نشد.'))},[]);
 useEffect(()=>{if(!KEY){setError('کلید نقشهٔ نشان هنوز برای سایت تنظیم نشده است.');return}let active=true;loadNeshan().then(L=>{if(!active||!host.current)return;mapRef.current=new L.Map(host.current,{key:KEY,maptype:'dreamy',center:[EVaz.lat,EVaz.lng],zoom:14});setReady(true)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false;markers.current.forEach(m=>m.remove());markers.current=[];mapRef.current?.remove();mapRef.current=null}},[]);
 useEffect(()=>{if(!ready||!mapRef.current)return;const L=window.L;markers.current.forEach(m=>m.remove());markers.current=[];const shown=items.filter(p=>filter==='همه'||(filter==='زمین'?isLand(p):!isLand(p)));for(const p of shown){const lat=Number(p.latitude),lng=Number(p.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng)||Math.abs(lat)>90||Math.abs(lng)>180)continue;const label=document.createElement('span');label.className=`evaz-price-pin ${isLand(p)?'land':'house'}`;label.textContent=price(p.asking_price_toman);const icon=L.divIcon({html:label,className:'evaz-price-icon',iconSize:[120,38],iconAnchor:[60,46]});const marker=L.marker([lat,lng],{icon,title:`${p.property_type}، ${price(p.asking_price_toman)}`}).addTo(mapRef.current).on('click',()=>setSelected(p));markers.current.push(marker)}},[items,filter,ready]);
 return <div className="map-page"><div className="map-toolbar"><div><h2>املاک روی نقشهٔ اوز</h2><p>زمین و خانه‌های دارای آگهی فعال</p></div><div className="map-filters" aria-label="فیلتر نوع ملک">{['همه','زمین','خانه'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>{setFilter(x);setSelected(null)}}>{x}</button>)}</div></div><div className="map-wrap"><div className="property-map" ref={host} role="application" aria-label="نقشه آگهی‌های املاک اوز"/>{error&&<div className="map-error" role="alert">{error}</div>}{!error&&items.length===0&&<div className="map-empty">هنوز آگهیِ دارای موقعیت روی نقشه ثبت نشده است.</div>}{selected&&<aside className="map-detail"><button className="map-close" onClick={()=>setSelected(null)} aria-label="بستن جزئیات">×</button><small>{selected.public_code} · {selected.region||'اوز'}</small><h3>{selected.property_type}</h3><strong>{price(selected.asking_price_toman)} تومان</strong><p>{selected.area_m2?`${Number(selected.area_m2).toLocaleString('fa-IR')} متر زمین`:''}{selected.building_area_m2?` · ${Number(selected.building_area_m2).toLocaleString('fa-IR')} متر زیربنا`:''}</p><a href="https://wa.me/989212745755" target="_blank" rel="noopener noreferrer">پرس‌وجو دربارهٔ این ملک</a></aside>}</div><p className="map-count">{items.filter(p=>filter==='همه'||(filter==='زمین'?isLand(p):!isLand(p))).length.toLocaleString('fa-IR')} آگهی روی نقشه</p></div>
}
