import {useEffect,useState,type FormEvent} from 'react';
const API='https://api.evazmelk.ir';
export type SellerUser={id:string;phone:string;name:string;marketing_opt_in:boolean};
type Props={user:SellerUser|null;onUser:(user:SellerUser|null)=>void;onRegister:()=>void};
export default function SellerAccount({user,onUser,onRegister}:Props){
 const [phone,setPhone]=useState(''),[code,setCode]=useState(''),[step,setStep]=useState<'phone'|'code'>('phone');
 const [name,setName]=useState(''),[consent,setConsent]=useState(false),[items,setItems]=useState<any[]>([]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{setName(user?.name||'');setConsent(user?.marketing_opt_in||false);if(user)fetch(`${API}/api/seller/my-submissions`,{credentials:'include'}).then(r=>r.ok?r.json():{items:[]}).then(d=>setItems(d.items||[])).catch(()=>setItems([]))},[user?.id]);
 async function send(path:string,body:object){const r=await fetch(API+path,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'درخواست انجام نشد');return d}
 async function requestCode(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await send('/api/seller/auth/request-code',{phone});setNotice(d.message);setStep('code')}catch(e){setError(e instanceof Error?e.message:'خطای اتصال')}finally{setBusy(false)}}
 async function verify(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await send('/api/seller/auth/verify-code',{phone,code});onUser(d.user);setNotice('ورود موفق بود. نام خود را ثبت کنید.')}catch(e){setError(e instanceof Error?e.message:'کد نامعتبر است')}finally{setBusy(false)}}
 async function saveProfile(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`${API}/api/seller/me`,{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,marketing_opt_in:consent})});const d=await r.json();if(!r.ok)throw Error(d.detail||'ثبت اطلاعات انجام نشد');onUser(d.user);setNotice('اطلاعات حساب ذخیره شد.')}catch(e){setError(e instanceof Error?e.message:'خطا در ذخیره')}finally{setBusy(false)}}
 async function logout(){await send('/api/seller/auth/logout',{});onUser(null);setCode('');setStep('phone');setNotice('از حساب خارج شدید.')}
 return <section className="content-section seller-page"><div className="page-heading"><span className="section-kicker">حساب خودمونی</span><h1>{user?'حساب من':'ورود یا ثبت‌نام'}</h1><p>برای ثبت ملک، شمارهٔ موبایل خود را با کد یک‌بارمصرف تأیید کنید.</p></div>
 {error&&<p role="alert" className="seller-error">{error}</p>}{notice&&<p role="status" className="seller-success">{notice}</p>}
 {!user?<div className="seller-step auth-panel">{step==='phone'?<form onSubmit={requestCode}><h2>شمارهٔ موبایل</h2><label>موبایل<input required type="tel" inputMode="tel" dir="ltr" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="09123456789"/></label><button className="seller-submit" disabled={busy}>ارسال کد ورود</button></form>:<form onSubmit={verify}><h2>کد پیامک‌شده</h2><p>کد شش‌رقمی ارسال‌شده به {phone} را وارد کنید.</p><label>کد ورود<input required type="text" inputMode="numeric" dir="ltr" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value)}/></label><button className="seller-submit" disabled={busy}>تأیید و ورود</button><button type="button" className="account-link" onClick={()=>{setStep('phone');setCode('')}}>تغییر شماره</button></form>}</div>:<><div className="seller-step auth-panel"><h2>مشخصات حساب</h2><p>شمارهٔ تأییدشده: <b dir="ltr">{user.phone}</b></p><form onSubmit={saveProfile}><label>نام و نام خانوادگی<input required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label className="consent-choice"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> مایل هستم پیامک‌های اطلاع‌رسانی و پیشنهادهای املاک خودمونی را دریافت کنم.</label><p className="seller-privacy">این انتخاب اختیاری است و هر وقت بخواهید می‌توانید آن را تغییر دهید.</p><button className="seller-submit" disabled={busy}>ذخیرهٔ حساب</button></form><div className="account-actions"><button type="button" onClick={onRegister}>ثبت ملک برای فروش</button><button type="button" onClick={logout}>خروج از حساب</button></div></div><div className="seller-step"><h2>درخواست‌های من</h2>{items.length?<ul className="seller-submissions">{items.map(x=><li key={x.id}><span>{({land:'زمین',villa:'خانهٔ ویلایی',apartment:'آپارتمان',mehr:'مسکن مهر',national:'مسکن ملی'} as Record<string,string>)[x.kind]||x.kind}</span><span>{({pending:'در انتظار بررسی',approved:'منتشرشده',rejected:'تأیید نشده'} as Record<string,string>)[x.status]||x.status}</span><small>{new Date(x.created_at).toLocaleDateString('fa-IR')}</small></li>)}</ul>:<p>هنوز درخواستی ثبت نکرده‌اید.</p>}</div></>}
 </section>
}
